### PR TITLE
Use usr/local/bin instead of usr/bin for Silverblue and other immutable OSs

### LINKED ISSUE #394: Not installable on Fedora Silverblue 36 (35 too)
Hello, 
I know this issue was fixed in the past but it seems to happen again. (see #129)
I was used to install it on Fedora workstation and it was working fine but since silverblue is on a read only system it seems to be unable to install it...

Also snap package doesn't seem to work

By the way keep going your software is super useful ^^ 

Thanks

### Error output:
```
[mimillie@fedora ~]$ sudo auto-cpufreq --install
[sudo] Mot de passe de mimillie : 

--------------------- Deploying auto-cpufreq as a daemon ----------------------

Traceback (most recent call last):
  File "/opt/auto-cpufreq/venv/bin/auto-cpufreq", line 4, in <module>
    __import__('pkg_resources').run_script('auto-cpufreq==1.9.3', 'auto-cpufreq')
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/auto_cpufreq-1.9.3-py3.10.egg/EGG-INFO/scripts/auto-cpufreq", line 226, in <module>
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/auto_cpufreq-1.9.3-py3.10.egg/EGG-INFO/scripts/auto-cpufreq", line 203, in main
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/auto_cpufreq-1.9.3-py3.10.egg/auto_cpufreq/core.py", line 350, in deploy_daemon
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/auto_cpufreq-1.9.3-py3.10.egg/auto_cpufreq/core.py", line 299, in cpufreqctl
  File "/usr/lib64/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/usr/bin/cpufreqctl.auto-cpufreq'

```
---

### System information:

OS: Fedora Linux 36.20220510.0 (Silverblue) x86_64
Kernel: 5.17.5-300.fc36.x86_64 
CPU: AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz
GPU: AMD ATI 04:00.0 Renoir

Add/paste output of:

```
[mimillie@fedora bin]$ sudo auto-cpufreq --debug
[sudo] Mot de passe de mimillie : 
Traceback (most recent call last):
  File "/opt/auto-cpufreq/venv/bin/auto-cpufreq", line 4, in <module>
    __import__('pkg_resources').run_script('auto-cpufreq==1.9.3', 'auto-cpufreq')
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/auto_cpufreq-1.9.3-py3.10.egg/EGG-INFO/scripts/auto-cpufreq", line 226, in <module>
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/auto_cpufreq-1.9.3-py3.10.egg/EGG-INFO/scripts/auto-cpufreq", line 146, in main
  File "/opt/auto-cpufreq/venv/lib64/python3.10/site-packages/auto_cpufreq-1.9.3-py3.10.egg/auto_cpufreq/core.py", line 299, in cpufreqctl
  File "/usr/lib64/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
OSError: [Errno 30] Read-only file system: '/usr/bin/cpufreqctl.auto-cpufreq'

```

#### Without providing requested information your issue might be ignored!

---

If installation failed with [auto-cpufreq-installer ](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer)have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?

### PR DESCRIPTION
**Pull request by gimbles**
Fixes #394

### CODE REVIEW

**Comment by AdnanHodzic** [comment]
Great stuff and thank you for your contribution!

**Comment by gimbles** [comment]
For future references: This should make it also compatible with OpenSUSE MicroOS and other immutable operating systems.

**Comment by SunkenHero** [comment]
Great work.

**Comment by AdnanHodzic** [comment]
@gimbles while reviewing #459 I noticed a particular regression introduced with this PR. 

Namely, prior to these changes if you perform an install auto-cpufreq with `sudo ./auto-cpufreq-installer --install` followed by installation of daemon `sudo auto-cpufreq --install`, then you decide to remove everything with `sudo ./auto-cpufreq-installer --remove` you'll get following output:

```
sudo ./auto-cpufreq-installer --remove 

--------------------- Removing auto-cpufreq daemon ----------------------

* Turn on bluetooth on boot

----------------------------------- Warning -----------------------------------

Detected GNOME Power Profiles daemon service is stopped!
This service will now be enabled and started again.

* Enabling GNOME power profiles
Removed "/etc/systemd/system/power-profiles-daemon.service".
Created symlink /etc/systemd/system/graphical.target.wants/power-profiles-daemon.service → /lib/systemd/system/power-profiles-daemon.service.

------------------ Running auto-cpufreq daemon removal script ------------------

* Stopping auto-cpufreq daemon (systemd) service

* Disabling auto-cpufreq daemon (systemd) at boot
Removed "/etc/systemd/system/multi-user.target.wants/auto-cpufreq.service".

* Removing auto-cpufreq daemon (systemd) unit file

* Reloading systemd manager configuration
reset failed

------------------------- auto-cpufreq daemon removed -------------------------

auto-cpufreq successfully removed.

-------------------------------------------------------------------------------


-------------------------------------------------------------------------------

auto-cpufreq tool and all its supporting files successfully removed.

-------------------------------------------------------------------------------
```

However, after these changes have been merged if you do the same steps as mentioned above, you'll only be presented with:

```
sudo ./auto-cpufreq-installer --remove 

-------------------------------------------------------------------------------

auto-cpufreq tool and all its supporting files successfully removed.

-------------------------------------------------------------------------------
```

I'd really like if same more verbose removal output was brought back as it gives more clarity to user on what happened. Can you please create a new PR for this? Thank you

**Comment by gimbles** [comment]
I don't really have an idea on why this regression is caused.

I didn't even touch the installer, just replaced a few paths in core.py

**Comment by AdnanHodzic** [comment]
> I don't really have an idea on why this regression is caused.
> 
> I didn't even touch the installer, just replaced a few paths in core.py

@gimbles I know, I'm also baffled myself. But have tracked it down where d77c1de commit (one before these changes were merged) doesn't have this behavior. 

@SunkenHero can you confirm if you have this problem as well?

**Comment by abvee** [comment]
The installer script just evaluates and runs `/usr/local/bin/auto-cpufreq --remove` when it tests that `auto-cpufreq-remove` exists. 

If this test fails, then it's likely that nothing is removed and the function silently goes on to print `auto-cpufreq tool and all its supporting files successfully removed.`

We should add a check to see if the test is successful or not, which would also help in debugging this particular issue. So something like this:

```
  if [ -f $srv_remove ]; then
    eval $tool_proc_rm
  else
  	separator
	printf "Failed to uninstall"
	separator
	return 1;
  fi
```

**Comment by AdnanHodzic** [comment]
> We should add a check in the installer to see if the test is successful or not, which would also help in debugging this particular issue. So something like this:
> 
> ```
>   if [ -f $srv_remove ]; then
>     eval $tool_proc_rm
>   else
>   	separator
> 	printf "Failed to uninstall"
> 	separator
> 	return 1;
>   fi
> ```

@abvee please give it a try and needless to say create a PR if you're successful :)

**Comment by abvee** [comment]
> @abvee please give it a try and needless to say create a PR if you're successful :)

I have some code, but I'm a bit lost on what to do with it. It's my first time actually contributing to a repository, so I'm not sure what best practice here is..... do I make a fork of @gimbles repository or just a new branch and PR on my own fork ?

**Comment by AdnanHodzic** [comment]
@abvee you would create a PR from auto-cpufreq `master` branch. Changes made in this PR by @gimbles have already been merged.

**Comment by abvee** [comment]
> @abvee you would create a PR from auto-cpufreq master branch. Changes made in this PR by @gimbles have already been merged.

But what about the changes I have made to the installer in #459 that have not been merged yet ? Do I modify the original install script and let you do the merging ? Sorry for all the unrelated questions, couldn't find any proper answers on google :(

**Comment by AdnanHodzic** [comment]
> But what about the changes I have made to the installer in https://github.com/AdnanHodzic/auto-cpufreq/pull/459 that have not been merged yet ? Do I modify the original install script and let you do the merging ?

Don't worry about it, I'll merge it as soon as this regression has been fixed. Reason why I didn't merge it yet is I'm trying to reduce entropy around this issue.

**Pull request merged**
