### PR TITLE
Added support for AMD. More refactoring

### LINKED ISSUE #17: Error: Couldn't find any of the necessary scaling governors. AMD CPU possibly not supported?
I got this error while running the tool with a AMD Ryzen 7 PRO 3700U cpu. 

If this error is indeed caused because the AMD cpu isn't supported, might I suggest updating the README to reflect this? If this isn't what's causing the error I'd have to look more into it and I'd gladly provide any needed information.

Output of `sudo tlp-stat -p`
```
--- TLP 1.2.2 --------------------------------------------

+++ Processor
CPU model      = AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = ondemand
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = ondemand performance schedutil 
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =  1400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  2300000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies = 2300000 1700000 1400000 [kHz]

(Idem for the remaining seven cores)

/sys/devices/system/cpu/cpufreq/boost                  = 1

x86_energy_perf_policy: unsupported CPU.

/sys/module/workqueue/parameters/power_efficient       = N
/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.
```

### PR DESCRIPTION
**Pull request by Red-Eyed**
fixes #17

- Added get_avail_powersave() (and performance).
  This function returns the most energy(and performance) efficient governor.
  This should fix AMD issue when powersave is not available
  but "ondemand" or "schedutil" are present

- Cleaned up and refactored.
  Added more convenient util functions.
  Also made it more pythonic, reduced subprocess calls, made it more modular

- Added support for setting turbo boost for AMD and Intel (intel_pstate and cpufreq driver)

- Tested on Intel and AMD machines and it works fine
    - It at least doesn't  fail
    - performance/powersave is 
    - turbo is switching on high CPU load.

- It needs more testing

### CODE REVIEW

**Comment by Red-Eyed** [comment]
@AdnanHodzic  please, don't review it. Just tried it on amd and have issues.

**Comment by Red-Eyed** [comment]
@AdnanHodzic now I tested it on AMD and fixed all related errors.

**Comment by Red-Eyed** [comment]
I would suggest to "squash merge" as I did a lot of garbage commits that should not be displayed in the master :)

**Comment by AdnanHodzic** [comment]
I'll definitely squash it before merging, so no worries about how many commits you make :)

However, I have problem testing the changes:

```
git checkout -b "Red-Eyed-fix_\#17_amd" "master"
fatal: 'Red-Eyed-fix_\#17_amd' is not a valid branch name.
git checkout -b "Red-Eyed:fix_#17_amd" "master"
fatal: 'Red-Eyed:fix_#17_amd' is not a valid branch name.
```

Could you maybe change the branch name so it doesn't have `#` in it (which I think is the problem with `bash`)?

**Comment by Red-Eyed** [comment]
yep, 1 min

**Comment by Red-Eyed** [comment]
recreated #67

**Comment by Red-Eyed** [comment]
@AdnanHodzic thanks for mentioned me in Release Notes!
I would change description for AMD `acpitz` -> [k10temp](https://www.kernel.org/doc/Documentation/hwmon/k10temp)

**Comment by AdnanHodzic** [comment]
> @AdnanHodzic thanks for mentioned me in Release Notes!

Of course! I had to find a way to thank you for the effort you put into this release :)

> I would change description for AMD: `acpitz` -> [k10temp](https://www.kernel.org/doc/Documentation/hwmon/k10temp)

Updated.

**Comment by fernando-inf** [comment]
Not function whit AMD V1605B:

`$ sudo auto-cpufreq --live

Note: You can quit live mode by pressing "ctrl+c"

----------------------------------- Warning -----------------------------------

Detected running GNOME Power Profiles daemon service!
This daemon might interfere with auto-cpufreq and has been disabled.

This daemon is not automatically disabled in "monitor" mode and
will be enabled after auto-cpufreq is removed.


-------------------------------------------------------------------------------


------------------ Checking for necessary scaling governors -------------------

ERROR:

Couldn't find any of the necessary scaling governors.

`

**Pull request closed without merging**
