### PR TITLE
Improved Python file structure (rename source > auto_cpufreq)

### PR DESCRIPTION
**Pull request by yochananmarqos**
This corrects the generic `/usr/lib/python3.9/site-packages/source/` > `/usr/lib/python3.9/site-packages/auto_cpufreq/`

Now we have matching proper folders:
```
/usr/lib/python3.9/site-packages/auto_cpufreq/
/usr/lib/python3.9/site-packages/auto_cpufreq-1.0-py3.9.egg-info/
``

### CODE REVIEW

**Comment by AdnanHodzic** [comment]
Makes sense, thanks for your contribution.

**Comment by yochananmarqos** [comment]
The `source` folder is still leftover on the remote side of both our reops, but not my local fork. I guess I must've done `mv` and `git add` instead of `git mv`. Oops.

**Comment by AdnanHodzic** [comment]
Do you want me to revert your last changes, or do you want to create a new PR with fix?

**Comment by yochananmarqos** [comment]
I guess I'll just do a quick new one since this is already done.

**Comment by yochananmarqos** [comment]
Done: #154

**Comment by yochananmarqos** [comment]
@crian One more change to the PKGBUILD needs to be done to reflect to folder name change. The last bit in the `sed` line needs to be changed from `source/core.py` to `auto_cpufreq/core.py`.

**Pull request merged**
