### PR TITLE
Ignore "Device or resource busy" error message when writing value

### PR DESCRIPTION
**Pull request by hingen**
Potential fix for the issue described in #563 by ignoring "write error: Device or resource busy" error message when writing a value.

### CODE REVIEW

**Comment by AdnanHodzic** [comment]
Thank you for the PR, since these changes seem strictly AMD oriented, I've asked [on auto-cpufreq discord channel](https://discord.gg/Sjauxtj6kH) if someone could test these changes.

**Comment by Tresillo2017** [comment]
Tried on my laptop with a Ryzen 7 and looks like it's not apearing anymore on journalctl but I have the same problem where on auto-cpufreq it shows that it can set EPP because it not supported
image

**Comment by AdnanHodzic** [comment]
@Tresillo2017 this issue was fixed with #631 can you make sure you have pulled the latest changes on `master` branch?

**Comment by shadeyg56** [comment]
I'm not sure this is related to #631 since that was a fix for Intel CPUs.

You're using the `acpi-cpufreq` driver which does not support EPP, so this is not a bug. If you would like EPP support, you'll need to switch to using `amd-pstate-epp`

**Comment by Tresillo2017** [comment]
> I'm not sure this is related to #631 since that was a fix for Intel CPUs.
> 
> You're using the `acpi-cpufreq` driver which does not support EPP, so this is not a bug. If you would like EPP support, you'll need to switch to using `amd-pstate-epp`

And how can I do that? By not typing anything into the grub parameters?

**Comment by AdnanHodzic** [comment]
> > I'm not sure this is related to #631 since that was a fix for Intel CPUs.
> > You're using the `acpi-cpufreq` driver which does not support EPP, so this is not a bug. If you would like EPP support, you'll need to switch to using `amd-pstate-epp`
> 
> And how can I do that? By not typing anything into the grub parameters?

Explained as part of: https://github.com/AdnanHodzic/auto-cpufreq/#troubleshooting

**Comment by Tresillo2017** [comment]
> > > I'm not sure this is related to #631 since that was a fix for Intel CPUs.
> > > You're using the `acpi-cpufreq` driver which does not support EPP, so this is not a bug. If you would like EPP support, you'll need to switch to using `amd-pstate-epp`
> > 
> > And how can I do that? By not typing anything into the grub parameters?
> 
> Explained as part of: https://github.com/AdnanHodzic/auto-cpufreq/#troubleshooting

That was a really quick reply, thx for that. And now it's working as supposed, let's se if my battery life improves I was getting 3-4h of battery life out of the box on a thinkpad e16 amd.

**Pull request closed without merging**
