### PR TITLE
Started the solution to Snap and PopOS not working

### PR DESCRIPTION
**Pull request by tyleraharrison**
Addresses issue #323 

Needs Snap detection on line 102/103

This code does NOT function properly unless that detection added

Added ability for the program to resume if the PopOS fix works

### CODE REVIEW

**Comment by bobslept** [comment]
Isn't it a snap only issue? After reading this comment from #240
> I got this error too when installing from Snap on Pop!OS 21.04. I was able to work around by installing with [git instead](https://github.com/AdnanHodzic/auto-cpufreq#auto-cpufreq-installer).

I've installed a VM with PopOS and the `distro` package from a python shell works just fine without changes.
If so it would be lot easier. On permission denied, detect file exists, detect snap, print solution.

I think snap detection is like this:
```
if os.getenv("PKG_MARKER") == "SNAP":
   # we are in snap package
```

**Comment by bobslept** [comment]
Just build 1.9.0 Snap from your repo, works like charm! :tada: 
```
beep@pop-os:~/auto-cpufreq-snap$ sudo auto-cpufreq --monitor
[!] Warning: Cannot get distro name
[!] Snap install on PopOS detected, you must manually run the following commands in another terminal:
 
[!] Backup the /etc/os-release file:
sudo mv /etc/os-release /etc/os-release-backup
 
[!] Create hardlink to /etc/os-release:
sudo ln /etc/pop-os/os-release /etc/os-release
 
[!] Aborting. Restart auto-cpufreq when you created the hardlink
beep@pop-os:~/auto-cpufreq-snap$ sudo mv /etc/os-release /etc/os-release-backup
beep@pop-os:~/auto-cpufreq-snap$ sudo ln /etc/pop-os/os-release /etc/os-release
beep@pop-os:~/auto-cpufreq-snap$ sudo auto-cpufreq --monitor
 
Note: You can quit monitor mode by pressing "ctrl+c"

-snip-
 
-------------------------------------------------------------------------------
 
Linux distro: Pop!_OS 20.04 LTS
Linux kernel: 5.15.5-76051505-generic
```

**Comment by AdnanHodzic** [comment]
I also think it's perfect! Great job @tyleraharrison and as always thank @bobslept for the assistance in review process :slightly_smiling_face: 

> If go this route, lets not forget to remove these lines:
> 
> https://github.com/AdnanHodzic/auto-cpufreq/blob/5332dffdb75568885483a92c6f2ec43a1093b59e/snap/snapcraft.yaml#L44-L52

I'll give Canonical folks few more days, but if it's not approved in few days when I'm doing a new release I'll take care of removing these lines.

**Comment by AdnanHodzic** [comment]
Changes live as part of [v1.9.0 release](https://github.com/AdnanHodzic/auto-cpufreq/releases).

**Pull request merged**
