### PR TITLE
Fix issue where epp cannot be set in `powersave` governor

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**
Fixes error in #725 according to the latest comments in #724

### CODE REVIEW

**Review by JunaidQrysh — CHANGES_REQUESTED** [review]
Add 'and gov == "performance":'
for intel as well

**Comment by TheChilledBuffalo** [comment]
Oh right, I'll add that

**Comment by TheChilledBuffalo** [comment]
Oops, the # 2 mention was an accident... was trying to say Number 2

**Comment by AdnanHodzic** [comment]
LGTM! Thank you for your contribution, you will be credited for your work as part of [future release](https://github.com/AdnanHodzic/auto-cpufreq/releases).

**Pull request merged**
