### PR TITLE
On laptops and notebooks, check if charging via BAT* status

### PR DESCRIPTION
**Pull request by AmitGolden**
Hi,
For some time now auto-cpufreq got stuck on the powersave governor for me.
This happens because Linux does not recognize my power adapter for some reason, thus using `grep . /sys/class/power_supply/A*/online` doesn't work for me.

I discussed this further in #234.

So, I changed `charging()` to read from `/sys/class/power_supply/BAT*/status` instead, which will greatly improve my experience.

### CODE REVIEW

**Comment by AdnanHodzic** [comment]
LGTM! Thank you your contribution and for chasing this one, much appreciated!

**Comment by MSCHELAK** [comment]
I have same issu and I have lenovo laptop

**Comment by MSCHELAK** [comment]
It happen becose conservation_mode

**Comment by AdnanHodzic** [comment]
@MSCHELAK can we please keep the discuss for problems that arose from this in #281? Thanks

**Pull request merged**
