### PR TITLE
WIP: Implement python virtual environment 

### PR DESCRIPTION
**Pull request by aroundthfur**
* added venv instead of using system env pip
  * adjusted the unit file to startup the app from the venv
  * created a wrapper script to call the app from the venv
  * extended cleanup for venv and additional scripts
  * refactored the is_running() function to find the process now that it
    is called from a venv

I tested this on Fedora 35. It worked fine (TM).
Please test on other platforms before merging. I am especially not sure how this change reflects on SNAP and other packaging systems.

### CODE REVIEW

**Comment by bobslept** [comment]
Could it be that power-profiles-daemon had something to do with it at the time of testing this?

**Comment by bobslept** [comment]
What would be the correct way of doing this. Merge his branch from the fork locally, work on it and push it as new PR and mention this PR in the new one? 

I can do it like that if you want. Not sure if it is the right way.

**Comment by AdnanHodzic** [comment]
> What would be the correct way of doing this. Merge his branch from the fork locally, work on it and push it as new PR and mention this PR in the new one?
> 
> I can do it like that if you want. Not sure if it is the right way.

Please do this. As I also got @aroundthfur consent to do this (make new PR on top of his changes) in the end I'll just credit you both.

**Comment by AdnanHodzic** [comment]
Changes live as part of [v1.9.0 release](https://github.com/AdnanHodzic/auto-cpufreq/releases).

**Pull request closed without merging**
