### PR TITLE
Refactroring and amd support

### LINKED ISSUE #17: Error: Couldn't find any of the necessary scaling governors. AMD CPU possibly not supported?
I got this error while running the tool with a AMD Ryzen 7 PRO 3700U cpu. 

If this error is indeed caused because the AMD cpu isn't supported, might I suggest updating the README to reflect this? If this isn't what's causing the error I'd have to look more into it and I'd gladly provide any needed information.

Output of `sudo tlp-stat -p`
```
--- TLP 1.2.2 --------------------------------------------

+++ Processor
CPU model      = AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx

/sys/devices/system/cpu/cpu0/cpufreq/scaling_driver    = acpi-cpufreq
/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor  = ondemand
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors = ondemand performance schedutil 
/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq  =  1400000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq  =  2300000 [kHz]
/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies = 2300000 1700000 1400000 [kHz]

(Idem for the remaining seven cores)

/sys/devices/system/cpu/cpufreq/boost                  = 1

x86_energy_perf_policy: unsupported CPU.

/sys/module/workqueue/parameters/power_efficient       = N
/proc/sys/kernel/nmi_watchdog                          = 0

+++ Undervolting
PHC kernel not available.
```

### PR DESCRIPTION
**Pull request by Red-Eyed**
fixes #17

- Added get_avail_powersave() (and performance).
  This function returns the most energy(and performance) efficient governor.
  This should fix AMD issue when powersave is not available
  but "ondemand" or "schedutil" are present

- Cleaned up and refactored.
  Added more convenient util functions.
  Also made it more pythonic, reduced subprocess calls, made it more modular

- Added support for setting turbo boost for AMD and Intel (intel_pstate and cpufreq driver)

- Tested on Intel and AMD machines and it works fine
    - It at least doesn't  fail
    - performance/powersave is switching correct
    - turbo is switching correct on high CPU load.

- It needs more testing

### CODE REVIEW

**Comment by AdnanHodzic** [comment]
On first look changes look good but I want to review it it bit better.

While everything works great with `auto-cpufreq-installer` and `auto-cpufreq` works as expected on Intel. When I create a snap out of these changes I run into following error:

```
Traceback (most recent call last):
  File "/snap/auto-cpufreq/x1/bin/auto-cpufreq", line 111, in <module>
    main()
  File "/snap/auto-cpufreq/x1/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/snap/auto-cpufreq/x1/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/snap/auto-cpufreq/x1/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/snap/auto-cpufreq/x1/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/snap/auto-cpufreq/x1/bin/auto-cpufreq", line 76, in main
    sysinfo()
  File "/snap/auto-cpufreq/x1/lib/python3.6/site-packages/source/core.py", line 395, in sysinfo
    searchfile = open("/var/lib/snapd/hostfs/etc/os-release", "r")
PermissionError: [Errno 13] Permission denied: '/var/lib/snapd/hostfs/etc/os-release'
```

Hence, I'm trying to figure out what this is about exactly before I merge this with master.

**Comment by Red-Eyed** [comment]
Yeah, this is exact problem happens on POP OS
Didn't u have such a problem on a master?

**Comment by Red-Eyed** [comment]
Yeah, want to get it merged, than want to start implementing config file

**Comment by AdnanHodzic** [comment]
Let's get this merged, this stuff is to good not to be part of master :) 

In meantime I'll deal with snap build problem, seems like something changed in snapd which I wasn't aware of.

**Pull request merged**
